import React from "react";
import { Button, Modal, ModalHeader, ModalBody, ModalFooter } from "reactstrap";


export default function CustomModal({ show, onClose, selectedCountry }) {

    return (
    <div>
        <Modal isOpen={show} toggle={onClose}>
        <ModalHeader onClose={onClose}>{selectedCountry.NAME_ENGL}
        </ModalHeader>
        <ModalBody>
            {/* <p>Capital: {selectedCountry.CAPT}</p> */}
            <p><b>Share of renewable energy in gross final energy consumption:</b> {selectedCountry.RENEW_ENERGY}% <br></br>
            <small> <i>The indicator measures the share of renewable energy consumption in gross final energy consumption according to the Renewable Energy Directive. The gross final energy consumption is the energy used by end-consumers (final energy consumption) plus grid losses and self-consumption of power plants.</i></small>
            </p>

            <p><b>Waste generation per capita:</b> {selectedCountry.TRASH_PER_CAPITA} kg <br></br>
            <small><i>The indicator is defined as total waste generated in a country including major mineral wastes (all NACE activities plus households), divided by the average population of the country.</i></small>
            </p>

            <p><b>Recycling rate of municipal waste:</b> {selectedCountry.RECYCLE}%<br></br>
            <small><i>The indicator measures the tonnage recycled from municipal waste divided by the total municipal waste arising. Recycling includes material recycling, composting and anaerobic digestion; and preparing for reuse. Municipal waste consists mostly of waste generated by households, but may also include similar wastes generated by small businesses and public institutions and collected by the municipality. This latter part of municipal waste may vary from municipality to municipality and from country to country, depending on the local waste management system. For areas not covered by a municipal waste collection scheme the amount of waste generated is estimated. The Member States report each year the amount recycled and the total municipal waste generated to Eurostat. Data collection, validation and dissemination are performed by the EDC Waste hosted at Eurostat.</i></small>
            </p>
            
        </ModalBody>
        <ModalFooter>
        <Button color="primary" onClick={onClose}>
            Close
        </Button>
        </ModalFooter>
        </Modal>
    </div>
    );
}
